### PR TITLE
cmake: check system jsoncpp version

### LINKED ISSUE #46: jsoncpp linker error when using system installation
Using system-wide jsoncpp installation sometimes causes linker error.
For example this one: 
```
opt/symbiotic/sbt-instrumentation/src/rewriter.cpp:162: undefined reference to `Json::CharReaderBuilder::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```
Maybe we need to check which version is installed in CMakeLists.

### PR DESCRIPTION
**Pull request by tomsik68**
If using system-wide installation of jsoncpp, we must make sure that the installed version is compatible. jsoncpp cmake module doesn't provide version information, so this PR uses pkg-config to find jsoncpp. 

This PR fixes #46.

### CODE REVIEW

**Comment by tomsik68** [comment]
I just tested the following in Docker:
1. remove pkg-config
2. clone sbt-instrumentation and checkout this branch
3. bootstrap dg and json
4. cmake .

CMake outputs the following line:
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```

CMake figures out pkg-config is not available, sets `JSON_FOUND` to false and the build continues as if the library wasn't available in the system.

**Comment by mchalupa** [comment]
Maybe I don't understand. If you bootstrap jsoncpp, shouldn't CMake use the bootstraped version instead of the system version? I think the problem should occur if you do not bootstrap jsoncpp, or not?

**Comment by tomsik68** [comment]
The problem occurs whenever there is an incompatible version of jsoncpp installed in the system. Bootstrapping jsoncpp doesn't imply that the bootstrapped version is used. Relevant section of CMakeLists:
```cmake
find_package(jsoncpp CONFIG)
if (jsoncpp_FOUND)
	set(JSON_LIBS jsoncpp_lib)
	message(STATUS "Using system jsoncpp library")
else()
	set(JSON_FILES jsoncpp.cpp)
endif()
```
Where `JSON_FILES` is used while compiling sbt-instr executable in [src/CMakeLists](https://github.com/staticafi/sbt-instrumentation/blob/0e0aca80ce770a73d2f82e91cae50e1ae824b89a/src/CMakeLists.txt#L13). And `JSON_LIBS` is used while linking the same executable.

**Comment by tomsik68** [comment]
I just did one more test where:
- jsoncpp is installed
- pkg-config isn't installed
- I didn't run bootstrap-json before build

The relevant part of output is:
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Checking for one of the modules 'jsoncpp'
-- Configuring done
CMake Error at src/CMakeLists.txt:8 (add_executable):
  Cannot find source file:
    jsoncpp.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at src/CMakeLists.txt:8 (add_executable):
  No SOURCES given to target: sbt-instr
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Pull request merged**
